FROM node:20-alpine
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build

WORKDIR /app/.medusa/server
RUN yarn install --production

EXPOSE 9000
CMD ["yarn", "start"]